development:
  AWS_BUCKET: "shopjedi.com"
  AWS_ACCESS_KEY_ID: "AKIAJRUNSYCX4OWQZXNA"
  AWS_SECRET_ACCESS_KEY: "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"
test:
  AWS_BUCKET: "shopjedi.com"
  AWS_ACCESS_KEY_ID: "AKIAJRUNSYCX4OWQZXNA"
  AWS_SECRET_ACCESS_KEY: "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"
production:
  AWS_BUCKET: "shopjedi.com"
  AWS_ACCESS_KEY_ID: "AKIAJRUNSYCX4OWQZXNA"
  AWS_SECRET_ACCESS_KEY: "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"
